openapi: 3.0.0
info:
  title: Agent as a service API
  version: 1.0.0
servers:
- description: Local server
  url: http://localhost:8080
paths:
  /chat:
    get:
      operationId: chat
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Chat'
          description: A Chat response
      summary: A chat response
      tags:
      - chat
components:
  schemas:
    Chat:
      example:
        id: id
        title: title
        content: content
      properties:
        id:
          type: string
        title:
          title: title
          type: string
        content:
          title: content
          type: string
      required:
      - content
      - title
      title: Document
      type: object
  securitySchemes: {}
