# coding: utf-8

"""
    Agent as a service API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from typing import Optional
from sqlmodel import SQLModel, Field

class Chat(SQLModel, table=True):
    
    id: Optional[str] = Field(default=None, primary_key=True)
    title: str = Field()
    content: str = Field()
